### ISSUE TITLE
would you please provide complete docker-compose.yaml with all components(like trino,dbt)?

### ISSUE THREAD

**Issue by shuitao** [zsvoboda/ngods-stocks#1]
would you please provide complete docker-compose.yaml with all components(like trino,dbt)?

**Comment by zsvoboda** [comment]
Hi, thank you for reporting this! I fixed the docker-compose file. Can you please pull the last change and try again? I'm wondering what OS and docker-compose you're running. My docker-compose seems to ignore these incorrect dependencies.

**Comment by shuitao** [comment]
Thank you, I'm using ubuntu 21.10, docker-compose 1.27.4,python 3.9
 after get new docker-compose.yml and run with docker-compose up -d
we get following error msg
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.9/http/client.py", line 1279, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1325, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1274, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1034, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 974, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.9/http/client.py", line 1279, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1325, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1274, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1034, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 974, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

**Comment by zsvoboda** [comment]
Can you please attach the full log of the docker-compose output? This sounds weird. I’ve just tested your config and it runs fine. Please pull the newest changes to this repo before you re-run the compose. Thanks!

**Comment by shuitao** [comment]
after reinstall docker-compose , it start  download, I will report the status after install，thank you。

**Comment by shuitao** [comment]
download and startup successful, following problem encoutered
1. I create a table with spark-sql cmd in spark docker, and I can connect to sparksql with metabase, but we can not browse tables in spark,. however we can select table and get data correctly, and see the table's info in pg.
2. when we try to exeute e2e.yaml, it report 
dagster.core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "download_yahoo_finance_files_op":
The above exception was caused by the following exception:
OSError: Cannot save file into a non-existent directory: '/var/lib/ngods/stage'

**Comment by NikitaKoposov** [comment]
hi! + 1 something wrong with trino
dagster.core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "create_schemas_op":

  File "/usr/local/lib/python3.9/site-packages/dagster/core/execution/plan/execute_plan.py", line 224, in dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/usr/local/lib/python3.9/site-packages/dagster/core/execution/plan/execute_step.py", line 353, in core_dagster_event_sequence_for_step
    for user_event in check.generator(
  File "/usr/local/lib/python3.9/site-packages/dagster/core/execution/plan/execute_step.py", line 69, in _step_output_error_checked_user_event_sequence
    for user_event in user_event_sequence:
  File "/usr/local/lib/python3.9/site-packages/dagster/core/execution/plan/compute.py", line 174, in execute_core_compute
    for step_output in _yield_compute_results(step_context, inputs, compute_fn):
  File "/usr/local/lib/python3.9/site-packages/dagster/core/execution/plan/compute.py", line 142, in _yield_compute_results
    for event in iterate_with_context(
  File "/usr/local/lib/python3.9/site-packages/dagster/utils/__init__.py", line 408, in iterate_with_context
    return
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/dagster/core/execution/plan/utils.py", line 73, in solid_execution_error_boundary
    raise error_cls(

The above exception was caused by the following exception:
requests.exceptions.ConnectionError: HTTPConnectionPool(host='trino', port=8060): Max retries exceeded with url: /v1/statement (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff2b1fabb0>: Failed to establish a new connection: [Errno 111] Connection refused'))

  File "/usr/local/lib/python3.9/site-packages/dagster/core/execution/plan/utils.py", line 47, in solid_execution_error_boundary
    yield
  File "/usr/local/lib/python3.9/site-packages/dagster/utils/__init__.py", line 406, in iterate_with_context
    next_output = next(iterator)
  File "/usr/local/lib/python3.9/site-packages/dagster/core/execution/plan/compute_generator.py", line 66, in _coerce_solid_compute_fn_to_iterator
    result = fn(context, **kwargs) if context_arg_provided else fn(**kwargs)
  File "/var/lib/ngods/dagster/db.py", line 36, in create_schemas_op
    cursor.execute("create schema if not exists warehouse.bronze with (location = 's3a://warehouse/bronze')")
  File "/usr/local/lib/python3.9/site-packages/trino/dbapi.py", line 436, in execute
    result = self._query.execute()
  File "/usr/local/lib/python3.9/site-packages/trino/client.py", line 525, in execute
    response = self._request.post(self._sql, additional_http_headers)
  File "/usr/local/lib/python3.9/site-packages/trino/client.py", line 339, in post
    http_response = self._post(
  File "/usr/local/lib/python3.9/site-packages/trino/exceptions.py", line 136, in decorated
    raise error
  File "/usr/local/lib/python3.9/site-packages/trino/exceptions.py", line 123, in decorated
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)

**Comment by zsvoboda** [comment]
[shuitao](https://github.com/shuitao) please pull the newest version of the repo (docker-compose and Dockerfiles) and remove the "spark" Docker image that is now deprecated. 

[nekkett](https://github.com/nekkett) are you on the latest version (aio image)?


Sorry for the difficulties.

**Comment by nekkett** [comment]
Yes, latest version.
It's ok) Thank's for sharing your exp!

**Comment by zsvoboda** [comment]
Can you share your aio container log, please?

**Comment by shuitao** [comment]
@zsvoboda aio is cool,
we can see metadata in metabase now,
but when we execute e2e script, still find follwing inf

dbt_bronze_run_op
ERROR
1 of 1 ERROR creating table model bronze.in_yahoo_finance....................... [ERROR in 1.51s]
09:01:55.020
dbt_bronze_run_op
INFO
Finished running 1 table model in 6.94s.
09:01:55.058
dbt_bronze_run_op
INFO
Completed with 1 error and 0 warnings:
09:01:55.072
dbt_bronze_run_op
ERROR
Runtime Error in model in_yahoo_finance (models/in_yahoo_finance.sql)
09:01:55.082
dbt_bronze_run_op
ERROR
  Database Error
09:01:55.091
dbt_bronze_run_op
ERROR
    org.apache.hive.service.cli.HiveSQLException: Error running query: [MISSING_COLUMN] org.apache.spark.sql.AnalysisException: cannot resolve '_c0' given input columns: []; line 14 pos 12;
09:01:55.099
dbt_bronze_run_op
ERROR
    'CreateTableAsSelect org.apache.iceberg.spark.SparkCatalog@710e5f9, bronze.in_yahoo_finance, [provider=iceberg], false
09:01:55.104
dbt_bronze_run_op
ERROR
    +- 'Project [cast('trim('_c0) as date) AS dt#15, 'trim('_c1) AS symbol#16, cast('trim('_c2) as decimal(32,16)) AS price_open#17, cast('trim('_c3) as decimal(32,16)) AS price_high#18, cast('trim('_c4) as decimal(32,16)) AS price_low#19, cast('trim('_c5) as decimal(32,16)) AS price_close#20, cast('trim('_c6) as bigint) AS volume#21, cast('trim('_c7) as decimal(32,16)) AS dividends#22, cast('trim('_c8) as decimal(32,16)) AS splits#23]
09:01:55.110
dbt_bronze_run_op
ERROR
       +- Relation [] csv

**Comment by zsvoboda** [comment]
Can you please taka a look at projects/dbt/bronze/logs/dbt.log? Please send me Java exception stack traces in this log file.

**Comment by zsvoboda** [comment]
Hey guys, any news? Did you succeed in running the demo?

**Comment by shuitao** [comment]
all compnents works！ it's great demo for us to experience datalake. 
just one problem, we can not browse the spark's table information in dbeaver, though we can operate the table correctly.
can you see all the tables in dbeaver?
we are using hive-jdbc-uber-2.6.3.0-235.jar to connect to sparksql in dbeaver

**Comment by shuitao** [comment]
> Unfortunately, I can't. There is an open issue for this in the dbeaver github. See [dbeaver/dbeaver#5314](https://github.com/dbeaver/dbeaver/issues/5314)

we impot kyubbi to connect between dbeaver and sparksql. we can saw all metadata

**Comment by zsvoboda** [comment]
I took a quick look at the Kyuubi, and it looks promising! I'll try to integrate it into the stack and let you know. Thanks!

**Comment by zsvoboda** [comment]
I tried it, and it works like a charm! THANK YOU!
