### ISSUE TITLE
requirements.txt - Python dependency resolution stops with an error

### ISSUE THREAD

**Issue by max-85** [zsvoboda/ngods-stocks#24]
365.9 WARNING: jsonschema 4.1.0 does not provide the extra 'format-nongpl'
365.9 WARNING: jsonschema 4.0.1 does not provide the extra 'format-nongpl'
365.9 WARNING: jsonschema 3.2.0 does not provide the extra 'format-nongpl'
366.0 WARNING: jsonschema 4.5.1 does not provide the extra 'format-nongpl'
366.0 WARNING: jsonschema 4.5.0 does not provide the extra 'format-nongpl'
366.0 WARNING: jsonschema 4.4.0 does not provide the extra 'format-nongpl'
366.0 WARNING: jsonschema 4.3.3 does not provide the extra 'format-nongpl'
366.0 WARNING: jsonschema 4.3.2 does not provide the extra 'format-nongpl'
366.0 WARNING: jsonschema 4.3.1 does not provide the extra 'format-nongpl'
366.0 WARNING: jsonschema 4.3.0 does not provide the extra 'format-nongpl'
366.0 WARNING: jsonschema 4.2.1 does not provide the extra 'format-nongpl'
366.0 WARNING: jsonschema 4.2.0 does not provide the extra 'format-nongpl'
366.0 WARNING: jsonschema 4.1.2 does not provide the extra 'format-nongpl'
366.0 WARNING: jsonschema 4.1.1 does not provide the extra 'format-nongpl'
366.0 WARNING: jsonschema 4.1.0 does not provide the extra 'format-nongpl'
366.0 WARNING: jsonschema 4.0.1 does not provide the extra 'format-nongpl'
366.0 WARNING: jsonschema 3.2.0 does not provide the extra 'format-nongpl'
366.2 WARNING: jsonschema 4.5.1 does not provide the extra 'format-nongpl'
366.2 WARNING: jsonschema 4.5.0 does not provide the extra 'format-nongpl'
366.2 WARNING: jsonschema 4.4.0 does not provide the extra 'format-nongpl'
366.2 WARNING: jsonschema 4.3.3 does not provide the extra 'format-nongpl'
366.2 WARNING: jsonschema 4.3.2 does not provide the extra 'format-nongpl'
366.2 WARNING: jsonschema 4.3.1 does not provide the extra 'format-nongpl'
366.2 WARNING: jsonschema 4.3.0 does not provide the extra 'format-nongpl'
366.2 WARNING: jsonschema 4.2.1 does not provide the extra 'format-nongpl'
366.2 WARNING: jsonschema 4.2.0 does not provide the extra 'format-nongpl'
366.2 WARNING: jsonschema 4.1.2 does not provide the extra 'format-nongpl'
366.2 WARNING: jsonschema 4.1.1 does not provide the extra 'format-nongpl'
366.2 WARNING: jsonschema 4.1.0 does not provide the extra 'format-nongpl'
366.2 WARNING: jsonschema 4.0.1 does not provide the extra 'format-nongpl'
366.2 WARNING: jsonschema 3.2.0 does not provide the extra 'format-nongpl'
366.3 WARNING: jsonschema 4.5.1 does not provide the extra 'format-nongpl'
366.3 WARNING: jsonschema 4.5.0 does not provide the extra 'format-nongpl'
366.3 WARNING: jsonschema 4.4.0 does not provide the extra 'format-nongpl'
366.3 WARNING: jsonschema 4.3.3 does not provide the extra 'format-nongpl'
366.3 WARNING: jsonschema 4.3.2 does not provide the extra 'format-nongpl'
366.3 WARNING: jsonschema 4.3.1 does not provide the extra 'format-nongpl'
366.3 WARNING: jsonschema 4.3.0 does not provide the extra 'format-nongpl'
366.4 INFO: pip is looking at multiple versions of pickleshare to determine which version is compatible with other requirements. This could take a while.
366.4   Downloading pickleshare-0.4.tar.gz (11 kB)
366.4   Preparing metadata (setup.py): started
366.6   Preparing metadata (setup.py): finished with status 'error'
366.6   error: subprocess-exited-with-error
366.6
366.6   × python setup.py egg_info did not run successfully.
366.6   │ exit code: 1
366.6   ╰─> [11 lines of output]
366.6       Traceback (most recent call last):
366.6         File "<string>", line 2, in <module>
366.6         File "<pip-setuptools-caller>", line 34, in <module>
366.6         File "/tmp/pip-install-40xfnxrc/pickleshare_118f0a7d8a57465088b38d568a6c39b0/setup.py", line 3, in <module>       
366.6           import pickleshare
366.6         File "/tmp/pip-install-40xfnxrc/pickleshare_118f0a7d8a57465088b38d568a6c39b0/pickleshare.py", line 41, in <module>
366.6           from path import path as Path
366.6         File "/tmp/pip-install-40xfnxrc/pickleshare_118f0a7d8a57465088b38d568a6c39b0/path.py", line 724
366.6           def mkdir(self, mode=0777):
366.6                                   ^
366.6       SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers       
366.6       [end of output]
366.6
366.6   note: This error originates from a subprocess, and is likely not a problem with pip.
366.6 error: metadata-generation-failed
366.6
366.6 × Encountered error while generating package metadata.
366.6 ╰─> See above for output.
366.6
366.6 note: This is an issue with the package mentioned above, not pip.
366.6 hint: See above for details.
366.7
366.7 [notice] A new release of pip is available: 23.0.1 -> 23.2.1
366.7 [notice] To update, run: pip install --upgrade pip
------
failed to solve: process "/bin/sh -c pip3 install --no-cache-dir -r requirements.txt     && rm requirements.txt" did not complete successfully: exit code: 1

**Comment by max-85** [comment]
Executed command: docker-compose up -d
-In VSCode/ a PowerShell terminal on Windows 11.

**Comment by climarocha** [comment]
@max-85 I needed to change the 51 line in aio/Dockerfile ... I added  **--use-deprecated legacy-resolver** to solve this problem.

**Comment by dedyoc** [comment]
@climarocha 
Can you export a more descriptive requirements file? I am struggling to make the dependencies work.
